export const data = [
	{
		id: 1,
		title: "Футболка UZcotton мужская",
		options: ["Цвет: белый", "Размер: 56"],
		warehouse: "Коледино WB",
		company: {
			name: "OOO Вайлдберриз",
			OGRN: "ОГРН: 1067746062449",
			address: "142181, Московская Область, Подольск, Д Коледино, Д. 6 СТР. 1",
		},
		price: 1051,
		discount: 522,
		discountDetails: [
			{ text: "Скидка 55%", num: 448 },
			{ text: "Скидка покупателя 10%", num: 81 },
		],
		amount: 1,
		amountTotal: 2,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/1.png",
		imagex2: "./files/img/supplies/1-x2.png, /files/img/supplies/1-x3.png",
	},
	{
		id: 2,
		title:
			"Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
		options: ["Цвет: прозрачный"],
		warehouse: "Коледино WB",
		company: {
			name: "OOO Мегапрофстиль",
			OGRN: "ОГРН: 5167746237148",
			address:
				"129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34",
		},
		price: 11500.235,
		discount: 10500.235,
		discountDetails: [
			{ text: "Скидка 55%", num: 300 },
			{ text: "Скидка покупателя 10%", num: 30 },
		],
		amount: 200,
		amountTotal: 500,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/2.png",
		imagex2: "./files/img/supplies/2-x2.png, /files/img/supplies/2-x3.png",
	},
	{
		id: 3,
		options: [],
		title:
			'Карандаши цветные Faber‑Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber‑Castell',
		warehouse: "Коледино WB",
		company: {
			name: "OOO Вайлдберриз",
			OGRN: "ОГРН: 1067746062449",
			address: "142181, Московская Область, Подольск, Д Коледино, Д. 6 СТР. 1",
		},
		price: 475,
		discount: 247,
		discountDetails: [
			{ text: "Скидка 55%", num: 193 },
			{ text: "Скидка покупателя 10%", num: 35 },
		],
		amount: 2,
		amountTotal: 2,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/3.png",
		imagex2: "./files/img/supplies/3-x2.png, /files/img/supplies/3-x3.png",
	},

	{
		id: 4,
		title: "Футболка UZcotton мужская",
		options: ["Цвет: белый", "Размер: 56"],
		warehouse: "Коледино WB",
		company: {
			name: "OOO Вайлдберриз",
			OGRN: "ОГРН: 1067746062449",
			address: "142181, Московская Область, Подольск, Д Коледино, Д. 6 СТР. 1",
		},
		price: 1051,
		discount: 522,
		discountDetails: [
			{ text: "Скидка 55%", num: 448 },
			{ text: "Скидка покупателя 10%", num: 81 },
		],
		amount: 1,
		amountTotal: 0,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/1.png",
		imagex2: "./files/img/supplies/1-x2.png, /files/img/supplies/1-x3.png",
	},
	{
		id: 5,
		title:
			"Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
		options: ["Цвет: прозрачный"],
		warehouse: "Коледино WB",
		company: {
			name: "OOO Мегапрофстиль",
			OGRN: "ОГРН: 5167746237148",
			address:
				"129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34",
		},
		price: 11500.235,
		discount: 11500.235,
		discountDetails: [
			{ text: "Скидка 55%", num: 300 },
			{ text: "Скидка покупателя 10%", num: 30 },
		],
		amount: 200,
		amountTotal: 0,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/2.png",
		imagex2: "./files/img/supplies/2-x2.png, /files/img/supplies/2-x3.png",
	},
	{
		id: 6,
		title:
			'Карандаши цветные Faber‑Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber‑Castell',
		options: [],
		warehouse: "Коледино WB",
		company: {
			name: "OOO Вайлдберриз",
			OGRN: "ОГРН: 1067746062449",
			address: "142181, Московская Область, Подольск, Д Коледино, Д. 6 СТР. 1",
		},
		price: 950,
		discount: 494,
		discountDetails: [
			{ text: "Скидка 55%", num: 193 },
			{ text: "Скидка покупателя 10%", num: 35 },
		],
		amount: 2,
		amountTotal: 0,
		delivery: [5.02, 6.02],
		image: "./files/img/supplies/3.png",
		imagex2: "./files/img/supplies/3-x2.png, /files/img/supplies/3-x3.png",
	},
];
